[package]
name = "virtual_keyboard"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
evdev-rs = { version = "0.6.0", features = ["serde"] }
libc = "0.2.126"
